### ISSUE TITLE
Need help copying jar file to GITHUB

### ISSUE THREAD

**Issue by byreshb** [shwethap/SeleniumPagefactory#1]
Hi 
There are two jar files in your local which they are not copied to GITHUB. Can you please copy them to lib folder of Java project and sync in the github software installed to update to cloud?

Project 'SeleniumPagefactory' is missing required library: 'C:\selenium-2.43.0\selenium-java-2.43.0-srcs.jar'   SeleniumPagefactory

Project 'SeleniumPagefactory' is missing required library: 'C:\selenium-2.43.0\selenium-java-2.43.0.jar'    SeleniumPagefactory

**Comment by shwethap** [comment]
HI Bairi,

my integration with maven is done let me know tomorr we can talk and then
add it in git hub. ok?
